//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQFinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemsPerPermission
    {
        public int id { get; set; }
        public string TypeOfPermision { get; set; }
        public string warehouse_fk { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> DateOFOperation { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public int Code_fk { get; set; }
        public string Name_item { get; set; }
    }
}
