//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQFinalProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Linq_EntityProjectEntities4 : DbContext
    {
        public Linq_EntityProjectEntities4()
            : base("name=Linq_EntityProjectEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<item_unit> item_unit { get; set; }
        public virtual DbSet<permission_item> permission_item { get; set; }
        public virtual DbSet<Permit> Permits { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Ware_to_from_Item> Ware_to_from_Item { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
    }
}
